version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chime-sdk-televisit-frontend"
s3_prefix = "chime-sdk-televisit-frontend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xdyvul6ryhyi"
parameter_overrides = "S3BucketNameForWebSite=\"chime-televisit-globex5\""
